src/main/java/br/com/siteapecof/bean/EventoBean.java
package br.com.siteapecof.bean;

import br.com.siteapecof.dao.EventoDAO;
import br.com.siteapecof.dao.ParticipanteDAO;
import br.com.siteapecof.entity.Evento;
import br.com.siteapecof.entity.Participante;
import br.com.siteapecof.util.Navigation;
import org.hibernate.HibernateException;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

@ManagedBean(name = "eventoBean")
@SessionScoped
public class EventoBean implements Serializable {

    private static final long serialVersionUID = 315437879648231893L;

    private EventoDAO eventoDAO = new EventoDAO();
    private ParticipanteDAO participanteDAO = new ParticipanteDAO();
    private Evento evento = new Evento();
    private List<Evento> eventos;
    private Double valor = new Double(0);

    @PostConstruct
    public void init() {
        if (eventos != null) {
            eventos = null;
        }
        eventos = new ArrayList<>();

    }

    public List<Evento> getAllEventos() {
        if (this.eventos != null) {
            eventos = new ArrayList<>();
        }
        eventos = eventoDAO.getAll();
        return eventos;
    }

    public List<Evento> eventosAtivos() {
        if (this.eventos != null) {
            eventos = new ArrayList<>();
        }
        eventos = eventoDAO.listarEventosAtivos();
        return eventos;
    }

    public String alterarEvento(Evento evento) {
        if (this.evento != null) {
            this.evento = null;
        }
        this.evento = evento;
        this.valor = evento.getValor();
        return Navigation.ALTERAR_EVENTO;
    }

    public String removerEvento(Evento evento) {
        this.eventoDAO.deleteEvento(evento);
        return Navigation.TODOS_EVENTOS;
    }

    public String removerParticipante(Participante participante) {
        this.participanteDAO.removerParticipante(participante);
        return Navigation.ALTERAR_EVENTO;
    }

    public String salvarEvento() {
        try {
            evento.setValor(valor);
            eventoDAO.atualizarOuCriarEvento(evento);
            evento = null;
            return Navigation.TODOS_EVENTOS;

        } catch (HibernateException ex) {
            ex.printStackTrace();
            return Navigation.NOVO_EVENTO;
        }
    }

    public String sobreEvento(Evento evento) {
        if (this.evento != null) {
            this.evento = null;
        }
        this.evento = evento;

        return "/visualizarEvento?faces-redirect=true";
    }


    public Double getValor() {
        return valor;
    }

    public void setValor(Double valor) {
        this.valor = valor;
    }

    public Evento getEvento() {
        return evento;
    }

    public void setEvento(Evento evento) {
        this.evento = evento;
    }

    public List<Evento> getEventos() {
        return eventos;
    }
}

src/main/java/br/com/siteapecof/bean/LoginBean.java
package br.com.siteapecof.bean;

import br.com.siteapecof.dao.UsuarioDAO;
import br.com.siteapecof.entity.Usuario;
import br.com.siteapecof.util.Navigation;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import java.io.Serializable;

/**
 * Created by Ayrton de Souza on 21/08/2016.
 */

@ManagedBean(name = "loginBean")
@ViewScoped
public class LoginBean implements Serializable {

    private static final long serialVersionUID = -7528096837474653010L;

    private UsuarioDAO usuarioDAO = new UsuarioDAO();
    private String email;
    private String senha;

    public String login() {
        Usuario usuario = usuarioDAO.getUsuario(this.email,this.senha);
        if (usuario == null) {
            FacesContext.getCurrentInstance().addMessage(
                    null,
                    new FacesMessage(FacesMessage.SEVERITY_ERROR, "Usuário não encontrado!",
                            "Erro no Login!"));

            return Navigation.LOGIN_PAGE;
        } else {
            FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put("currentUser", usuario);
            return Navigation.TODOS_EVENTOS;
        }
    }

    public String getEmail() {
        return email;
    }

    public String getSenha() {
        return senha;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }
}

src/main/java/br/com/siteapecof/bean/NoticiaBean.java
package br.com.siteapecof.bean;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import br.com.siteapecof.util.Navigation;
import br.com.siteapecof.util.UploadImagem;
import org.primefaces.event.FileUploadEvent;

import br.com.siteapecof.dao.NoticiaDAO;
import br.com.siteapecof.entity.Noticia;
import org.primefaces.model.UploadedFile;

import java.io.File;
import java.util.List;

@ManagedBean
@SessionScoped
public class NoticiaBean {
	
	private Noticia noticia = new Noticia();
	private NoticiaDAO noticiaDAO = new NoticiaDAO();
    private UploadImagem imagem = new UploadImagem();
	
		
	public void handleFileUpload(FileUploadEvent event) {
            this.imagem.fileUpload(event,".jpg","/noticia/");
            this.noticia.setImagem(this.imagem.getNome());
            FacesMessage message = new FacesMessage("Succesful", event.getFile().getFileName() + " is uploaded.");
            FacesContext.getCurrentInstance().addMessage(null, message);

	}

    public String salvarNoticia(){
        noticiaDAO.adicionarNoticia(noticia);
        this.imagem.gravar();

        this.noticia = new Noticia();
        this.imagem = new UploadImagem();

        return Navigation.TODOAS_NOTICIAS;
    }

    public List<Noticia> getAllNoticias(){
        return  noticiaDAO.getAllNoticiasOrderByDate();
    }



	public Noticia getNoticia() {
		return noticia;
	}

    public void setNoticia(Noticia noticia) {
		this.noticia = noticia;
	}


    public String editarNoticia(Noticia noticia) {
        this.noticia = noticia;
        return Navigation.N0VA_NOTICIA;
    }
}

src/main/java/br/com/siteapecof/bean/UsuarioBean.java
package br.com.siteapecof.bean;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import br.com.siteapecof.dao.UsuarioDAO;
import br.com.siteapecof.entity.TipoUsuario;
import br.com.siteapecof.entity.Usuario;
import br.com.siteapecof.util.Navigation;
import org.hibernate.JDBCException;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

@ManagedBean(name = "usuarioBean")
@SessionScoped
public class UsuarioBean implements Serializable {


    private static final long serialVersionUID = 7428046837474353010L;

    private Usuario usuario = new Usuario();
    private UsuarioDAO usuarioDAO = new UsuarioDAO();
    private List<Usuario> diretores;
    private List<Usuario> usuarios;

    @PostConstruct
    public void init() {
        diretores = new ArrayList<>();
        diretores = usuarioDAO.listarDiretores();
        //FacesContext.getCurrentInstance().getExternalContext().getSession(true);
    }


    public void cadastroUsuario() {

        usuarioDAO.adicionarUsuario(usuario);
        usuario = new Usuario();
    }

    public String editarUsuario(Usuario usuario){
        if(usuario != null){
            usuario = null;
        }
            this.usuario = usuario;

        return Navigation.NOVO_USUARIO;
    }

    public String deletarUsuario(Usuario usuario){
        usuarioDAO.removerUsuario(usuario);
        return Navigation.TODOS_USUARIOS;
    }



    public String logout() {
        FacesContext.getCurrentInstance().getExternalContext().getSessionMap().remove("currentUser");
        usuario = null;
        return Navigation.LOGIN_PAGE;
    }

    public List<Usuario> getAllUsuarios() {
        if (usuarios == null) {
            usuarios = new ArrayList<>();
        }
        usuarios = usuarioDAO.getAll();

        return this.usuarios;
    }

    public List<Usuario> getDiretores() {
        return diretores;
    }

    public void setDiretores(List<Usuario> diretores) {
        this.diretores = diretores;
    }

    public UsuarioDAO getUsuarioDAO() {
        return usuarioDAO;
    }

    public void setUsuarioDAO(UsuarioDAO usuarioDAO) {
        this.usuarioDAO = usuarioDAO;
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public TipoUsuario[] getTipoUsuarios() {
        return TipoUsuario.values();
    }


}

src/main/webapp/apecof/alterarEvento.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
<h:head>


</h:head>
<h:body>
    <h:form>
        <p:panelGrid style="margin-top:20px">
            <f:facet name="header">
                <p:row>
                    <p:column colspan="2">Cadastro de Evento</p:column>
                </p:row>
                <p:row>
                    <p:column colspan="1">Titulo</p:column>
                    <p:column colspan="1"><p:inputText id="tituloEvento" placeholder="ex. Evento de Forense"
                                                       value="#{eventoBean.evento.titulo}"/></p:column>
                </p:row>
                <p:row>
                    <p:column colspan="1">Data Evento</p:column>
                    <p:column colspan="1">
                        <p:inputMask id="dataEvento" placeholder="ex. 22/01/2016" mask="99-99-9999"
                                     value="#{eventoBean.evento.dataEvento}">
                            <f:convertDateTime pattern="dd-MM-yyyy"/>
                        </p:inputMask>
                    </p:column>
                </p:row>
                <p:row>
                    <p:column colspan="1">Data Fim Inscricao</p:column>
                    <p:column colspan="1">
                        <p:inputMask id="dataFimInscricao" placeholder="ex. 22/01/2016" mask="99-99-9999"
                                     value="#{eventoBean.evento.dataFimInscricao}">
                            <f:convertDateTime pattern="dd-MM-yyyy"/>
                        </p:inputMask>
                    </p:column>
                </p:row>
                <p:row>
                    <p:column colspan="1">Valor</p:column>
                    <p:column colspan="1">
                        <p:inputNumber id="valorEvento" placeholder="R$223.45" value="#{eventoBean.valor}" symbol=" R$"
                                       symbolPosition="s" decimalSeparator="," thousandSeparator="."/>
                    </p:column>
                </p:row>
                <p:row>
                    <p:column colspan="1">Descricao</p:column>
                    <p:column colspan="1">
                        <p:inputTextarea value="#{eventoBean.evento.descricao}" rows="5" cols="30" maxlength="10"
                                         counterTemplate="{0} characters remaining." autoResize="false"/>
                    </p:column>
                </p:row>
                <p:row>
                    <p:dataTable var="participante" value="#{eventoBean.evento.participantes}">
                        <p:column headerText="Nome">
                            <h:outputText value="#{participante.nome}"/>
                        </p:column>

                        <p:column headerText="email">
                            <h:outputText value="#{participante.email}">

                            </h:outputText>
                        </p:column>

                        <p:column headerText="Telefone">
                            <h:outputText value="#{participante.telefone}">

                            </h:outputText>
                        </p:column>
                        <p:column style="text-align:center">
                            <f:facet name="header">Alterar</f:facet>
                            <h:commandButton action="#{eventoBean.alterarEvento(evento)}"
                                             value="Editar" styleClass="btn btn-warning"/>
                        </p:column>
                        <p:column style="text-align:center">
                            <f:facet name="header">Deletar</f:facet>
                            <h:commandButton action="#{eventoBean.removerParticipante(participante)}"
                                             value="Deletar" styleClass="ui-btn-active"/>
                        </p:column>
                    </p:dataTable>
                </p:row>
            </f:facet>
        </p:panelGrid>

        <p:commandButton value="Cadastrar" id="btnCadastrar" action="#{eventoBean.salvarEvento}" ajax="false"/>
    </h:form>
</h:body>
</html>

src/main/webapp/apecof/cadastroEvento.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/template.xhtml">

    <ui:define name="content">
        <div class="container">
            <h:form>
                <p:tabView>

                    <p:tab title="Cadastro">

                        <div class="row">
                            <div class="col-sm-12">
                                <h:outputLabel value="Titulo: "/>
                                <p:inputText value="#{eventoBean.evento.titulo}"
                                             styleClass="form-control"/>
                            </div>
                            <br/>
                            <div class="col-sm-12">
                                <h:outputLabel value="Data do evento: "/>
                                <p:inputMask id="dataEvento" placeholder="ex. 22/01/2016" mask="99-99-9999"
                                             value="#{eventoBean.evento.dataEvento}"
                                             styleClass="form-control">
                                    <f:convertDateTime pattern="dd-MM-yyyy"/>
                                </p:inputMask>
                            </div>
                        </div>
                        <br/>
                        <div class="row">
                            <div class="col-sm-12">
                                <h:outputLabel value="Incrição até: "/>
                                <p:inputMask id="dataFimInscricao" placeholder="ex. 22/01/2016" mask="99-99-9999"
                                             value="#{eventoBean.evento.dataFimInscricao}"
                                             styleClass="form-control">
                                    <f:convertDateTime pattern="dd-MM-yyyy"/>
                                </p:inputMask>
                            </div>
                            <br/>
                            <div class="col-sm-12">
                                <h:outputLabel value="Valor do evento: "/>
                                <p:inputNumber id="valorEvento" placeholder="R$223.45" value="#{eventoBean.valor}"
                                               symbol=" R$" symbolPosition="s" decimalSeparator=","
                                               thousandSeparator="."
                                               styleClass="form-control"/>
                            </div>
                            <br/>
                            <div class="col-sm-12">
                                <h:outputLabel value="Descrição: "/>
                                <p:inputTextarea value="#{eventoBean.evento.descricao}" rows="5" cols="30"
                                                 maxlength="5000"
                                                 counterTemplate="{0} characters remaining." autoResize="false"
                                                 styleClass="form-control"/>
                            </div>
                        </div>
                        <br/>
                        <div class="row">
                            <div class="form-group">
                                <div class="col-sm-12 botao">
                                    <p:commandButton id="botao"
                                                     action="#{eventoBean.salvarEvento}"
                                                     value="Salvar"
                                                     styleClass="btn btn-success"/>

                                </div>
                            </div>
                        </div>
                    </p:tab>
                </p:tabView>
            </h:form>
        </div>
    </ui:define>
</ui:composition>

src/main/webapp/apecof/cadastroUsuario.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/template.xhtml">

    <ui:define name="content">
        <p:messages errorClass="alert-danger" infoClass="alert-sucess"/>
        <h:form>
            <p:panelGrid style="margin-top:20px">
                <f:facet name="header">
                    <p:row>
                        <p:column colspan="2">Cadastro de Usuario</p:column>
                    </p:row>
                    <p:row>
                        <p:column colspan="1">Nome</p:column>
                        <p:column colspan="1"><p:inputText id="nomeUsuario" placeholder="ex. Francisco"
                                                           value="#{usuarioBean.usuario.nome}"/></p:column>
                    </p:row>
                    <p:row>
                        <p:column colspan="1">Sobrenome</p:column>
                        <p:column colspan="1"><p:inputText id="sobrenomeUsuario" placeholder="ex. Sousa Neto"
                                                           value="#{usuarioBean.usuario.snome}"/></p:column>
                    </p:row>
                    <p:row>
                        <p:column colspan="1">Email</p:column>
                        <p:column colspan="1"><p:inputText id="emailUsuario" placeholder="eu@gmail.com"
                                                           value="#{usuarioBean.usuario.email}"/></p:column>
                    </p:row>
                    <p:row>
                        <p:column colspan="1">Telefone</p:column>
                        <p:column colspan="1">
                            <p:inputMask id="telefonelUsuario" placeholder="Ex. (85)9899-99999"
                                         value="#{usuarioBean.usuario.telefone}"
                                         mask="(99)9999-99999"/></p:column>
                    </p:row>
                    <p:row>
                        <p:column>Cargo</p:column>
                        <p:column><p:selectOneMenu id="cargo" value="#{usuarioBean.usuario.cargo}" style="width:125px">
                            <f:selectItem itemLabel="Selecione" itemValue=""/>
                            <f:selectItem itemLabel="Presidente" itemValue="Presidente"/>
                            <f:selectItem itemLabel="Vice-Presidente" itemValue="Vice-Presidente"/>
                            <f:selectItem itemLabel="Primeiro Tesoureiro" itemValue="Primeiro Tesoureiro"/>
                            <f:selectItem itemLabel="Primeiro Secretário" itemValue="Primeiro Secretário"/>
                            <f:selectItem itemLabel="Segundo Tesoureiro" itemValue="Primeiro Tesoureiro"/>
                            <f:selectItem itemLabel="Segundo Secretário" itemValue="Primeiro Secretário"/>
                        </p:selectOneMenu>
                        </p:column>
                    </p:row>
                    <p:row>
                        <p:column colspan="1">Tipo De Usuario</p:column>
                        <p:column colspan="1"><p:selectOneMenu id="tipoUsuario"
                                                               value="#{usuarioBean.usuario.tipoUsuario}"
                                                               style="width:125px">
                            <f:selectItems value="#{usuarioBean.tipoUsuarios}" var="a"
                                           itemValue="#{a}" itemLabel="#{a.descricao}"/>
                        </p:selectOneMenu></p:column>
                    </p:row>
                    <p:row>
                        <p:column colspan="1">Tratamento</p:column>
                        <p:column colspan="1"><p:selectOneMenu id="tratamento" value="#{usuarioBean.usuario.tratamento}"
                                                               style="width:125px">
                            <f:selectItem itemLabel="Selecione" itemValue=""/>
                            <f:selectItem itemLabel="Sr" itemValue="Sr"/>
                            <f:selectItem itemLabel="Prof." itemValue="Prof."/>
                            <f:selectItem itemLabel="Dr." itemValue="Dr."/>
                            <f:selectItem itemLabel="Tenente" itemValue="Tenente"/>
                        </p:selectOneMenu></p:column>
                    </p:row>
                    <p:row>
                        <p:column colspan="1">Link Lattes</p:column>
                        <p:column colspan="1"><p:inputText id="linkLattes"
                                                           placeholder="Ex. http://cnpq.lattes.gov.br/....."
                                                           value="#{usuarioBean.usuario.linkLattes}"/></p:column>
                    </p:row>

                    <p:row>
                        <p:column colspan="1">Senha</p:column>
                        <p:column colspan="1"> <p:password id="senha" value="#{usuarioBean.usuario.senha}"
                                                           feedback="true"/>
                        </p:column>
                    </p:row>
                    <p:row>
                        <p:column>Mini Curriculo</p:column>
                        <p:column colspan="1"><p:inputTextarea rows="5" cols="30" counter="display" maxlength="500"
                                                               counterTemplate="Faltando {0} caracteres"
                                                               autoResize="false"
                                                               value="#{usuarioBean.usuario.miniCurriculo}"/></p:column>
                    </p:row>
                    <p:row>
                        <p:column></p:column>
                        <p:column><h:outputText id="display"/></p:column>
                    </p:row>

                </f:facet>

            </p:panelGrid>
            <h:commandButton value="Cadastrar" id="btnCadastrar" action="#{usuarioBean.cadastroUsuario}"/>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/apecof/login.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/template_login.xhtml">

    <ui:define name="metatag">
        <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    </ui:define>
    <ui:define name="content">
        <div id="wrapper">

            <h:form id="login-form" styleClass="login-form">

                <div class="header">
                    <img src="/imagens/logo.jpg"/>
                    <h1>Apecof</h1>
                    <span>Bem Vindo</span>
                </div>

                <div class="content">
                    <p:inputText id="username" styleClass="input username"
                                 value="#{loginBean.email}"
                                 placeholder="Email: exemplo@example.com"/>
                    <div class="user-icon"/>
                    <p:password id="password" styleClass="input password"
                                value="#{loginBean.senha}"
                                placeholder="Senha"/>
                    <div class="pass-icon"/>
                </div>

                <div class="footer">
                    <h:commandButton id="login" value="Entrar"
                                     styleClass="button" action="#{loginBean.login()}"/>

                </div>
            </h:form>
        </div>
        <div class="gradient"></div>
    </ui:define>
</ui:composition>

src/main/webapp/apecof/visualizaTodosEventos.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/template.xhtml">


    <ui:define name="content">
        <div class="container">
            <h:form id="form">
                <p:dataTable var="evento" value="#{eventoBean.allEventos}" styleClass="table">
                    <p:column headerText="Codigo">
                        <h:outputText value="#{evento.id}"/>
                    </p:column>

                    <p:column headerText="Titulo">
                        <h:outputText value="#{evento.titulo}"/>
                    </p:column>

                    <p:column headerText="Brand">
                        <h:outputText value="#{evento.dataEvento}">
                            <f:convertDateTime pattern="dd/MM/yyyy"/>
                        </h:outputText>
                    </p:column>

                    <p:column headerText="Insrições Até">
                        <h:outputText value="#{evento.dataFimInscricao}">
                            <f:convertDateTime pattern="dd/MM/yyyy"/>
                        </h:outputText>
                    </p:column>
                    <p:column headerText="Valor">
                        <h:outputText value="#{evento.valor}"/>
                    </p:column>
                    <p:column headerText="Participantes">
                        <h:outputText value="#{evento.participantes.size()}"/>
                    </p:column>
                    <p:column style="text-align:center">
                        <f:facet name="header">Alterar</f:facet>
                        <h:commandButton action="#{eventoBean.alterarEvento(evento)}"
                                         value="Editar" styleClass="btn btn-warning"/>
                    </p:column>
                    <p:column style="text-align:center">
                        <f:facet name="header">Deletar</f:facet>
                        <h:commandButton action="#{eventoBean.removerEvento(evento)}"
                                         value="Deletar" styleClass="btn btn-danger"/>
                    </p:column>

                </p:dataTable>
            </h:form>
        </div>
    </ui:define>
</ui:composition>

src/main/webapp/apecof/visualizarNoticias.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/template.xhtml">


    <ui:define name="content">
        <div class="container">
            <h:form id="form">
                <p:dataTable var="noticia" value="#{noticiaBean.allNoticias}" styleClass="table">
                    <p:column headerText="Nome">
                        <h:outputText value="#{noticia.titulo}"/>
                    </p:column>

                    <p:column headerText="Email">
                        <h:outputText value="#{noticia.dataPostagem}"/>
                    </p:column>
                    <p:column style="text-align:center">
                        <f:facet name="header">Alterar</f:facet>
                        <h:commandButton action="#{noticiaBean.editarNoticia(noticia)}"
                                         value="Editar" styleClass="btn btn-warning"/>
                    </p:column>
                    <p:column style="text-align:center">
                        <f:facet name="header">Deletar</f:facet>
                        <h:commandButton action="#{usuarioBean.deletarUsuario(usuario)}"
                                         value="Deletar" styleClass="btn btn-danger"/>
                    </p:column>

                </p:dataTable>
            </h:form>
        </div>
    </ui:define>
</ui:composition>

src/main/webapp/apecof/visualizarUsuarios.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/template.xhtml">


    <ui:define name="content">
        <div class="container">
            <h:form id="form">
                <p:dataTable var="usuario" value="#{usuarioBean.allUsuarios}" styleClass="table">
                    <p:column headerText="Nome">
                        <h:outputText value="#{usuario.nome}"/>
                    </p:column>

                    <p:column headerText="Email">
                        <h:outputText value="#{usuario.email}"/>
                    </p:column>

                    <p:column headerText="Cargo">
                        <h:outputText value="#{usuario.cargo}"/>
                    </p:column>
                    <p:column headerText="Tipo Usuario">
                        <h:outputText value="#{usuario.tipoUsuario.descricao}"/>
                    </p:column>
                    <p:column style="text-align:center">
                        <f:facet name="header">Alterar</f:facet>
                        <h:commandButton action="#{usuarioBean.editarUsuario(usuario)}"
                                         value="Editar" styleClass="btn btn-warning"/>
                    </p:column>
                    <p:column style="text-align:center">
                        <f:facet name="header">Deletar</f:facet>
                        <h:commandButton action="#{usuarioBean.deletarUsuario(usuario)}"
                                         value="Deletar" styleClass="btn btn-danger"/>
                    </p:column>

                </p:dataTable>
            </h:form>
        </div>
    </ui:define>
</ui:composition>